=== techcybersims/cybersims/localComps.dtd
<!ELEMENT CompName (HostName,UserName,Password,Note)>
<!ELEMENT HostName (#PCDATA)>
<!ELEMENT UserName (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Note (#PCDATA)>

=== techcybersims/cybersims/localCompsE.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "localComps.dtd">
<CompName>
<HostName>TheeiMac</HostName>
<UserName>raysims</UserName>
<Password>Z00m!__!</Password>
<UserName>judi</UserName>
<Password>JS10151957</Password>
<Note>OSX 10.11.</Note>
<HostName>shminimac</HostName>
<UserName>raysims</UserName>
<Password>Z00m!__!</Password>
<UserName>sysadmin</UserName>
<Password>L00k@me!__!</Password>
<Note>OSX 10.13.</Note>
<HostName>cyberimac</HostName>
<UserName>raysims</UserName>
<Password>Z00m!__!</Password>
<UserName>sa</UserName>
<Password>L00k@me!__!</Password>
<UserName>judi</UserName>
<Password>JS10151957</Password>
<Note>OSX 10.13.</Note>
<HostName>nuc-i7</HostName>
<UserName>ray@cybersims.com</UserName>
<Password>!*Swis@93063</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>W10 Pro</Note>
<HostName>LatD620</HostName>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<UserName>sims.ray@outlook.com</UserName>
<Password>!*Swis@93063</Password>
<Note>W10 Pro</Note>
<HostName>LatD830</HostName>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<UserName>raylsims1@outlook.com</UserName>
<Password>!*Swis@93063</Password>
<Note>W10 Pro</Note>
<HostName>JS-E6410</HostName>
<UserName>judi</UserName>
<Password>js101557</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>W10 Pro</Note>
<HostName>garageLat2</HostName>
<UserName>ray</UserName>
<Password>Z00m!__!</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>Fedoara 27</Note>
<HostName>CoreI3</HostName>
<UserName>rsims</UserName>
<Password>Z00m!__!</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>Fedora 27</Note>
<HostName>coreIIzorin</HostName>
<UserName>rsims</UserName>
<Password>Z00m!__!</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>Zorin Pro</Note>
<HostName>latd410</HostName>
<UserName>root</UserName>
<Password>L00k@me!__!</Password>
<UserName>tech</UserName>
<Password>N3tm@n!__!</Password>
<Note>Kali Linux</Note>
<HostName>w7eeepc</HostName>
<UserName>ray</UserName>
<Password>z00m!1</Password>
<Note>keyboard issue</Note>
<HostName>cybermacbook</HostName>
<UserName>ray</UserName>
<Password>Z00m!__!</Password>
<UserName>admin</UserName>
<Password>L00k@me!__!</Password>
<Note>Has Photoshop CS5</Note>
</CompName>
